[INFO] [2020-10-29 08:05:14,341] [1863:140046620854080] - task_executor.py[line:121]: run 202010290805128735466 dataio_0 202010290805128735466_dataio_0 host 10000 task
[INFO] [2020-10-29 08:05:14,341] [1863:140046620854080] - task_executor.py[line:122]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'job_parameters': {'work_mode': 0, 'processors_per_node': 1, 'align_task_input_data_partition': True, 'model_id': 'arbiter-10000#guest-9999#host-10000#model', 'model_version': '202010290805128735466'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[INFO] [2020-10-29 08:05:14,342] [1863:140046620854080] - task_executor.py[line:123]: {'data': {'data': ['args.train_data']}}
[DEBUG] [2020-10-29 08:05:14,343] [1863:140046620854080] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0008993148803710938s
[INFO] [2020-10-29 08:05:14,343] [1863:140046620854080] - task_executor.py[line:202]: start save as task 202010290805128735466_dataio_0 input data table fate_flow_test_breast_hetero breast_hetero_host
[DEBUG] [2020-10-29 08:05:14,344] [1863:140046620854080] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008554458618164062s
[DEBUG] [2020-10-29 08:05:14,357] [1863:140046620854080] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.01245880126953125s
[INFO] [2020-10-29 08:05:14,360] [1863:140046620854080] - task_executor.py[line:218]: save as task 202010290805128735466_dataio_0 input data table to 202010290805128735466_dataio_0_host_10000 breast_hetero_host done
[DEBUG] [2020-10-29 08:05:14,492] [1863:140046620854080] - component_properties.py[line:67]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': False, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'job_parameters': {'work_mode': 0, 'processors_per_node': 1, 'align_task_input_data_partition': True, 'model_id': 'arbiter-10000#guest-9999#host-10000#model', 'model_version': '202010290805128735466'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[DEBUG] [2020-10-29 08:05:14,492] [1863:140046620854080] - component_properties.py[line:74]: need_run: True, need_cv: False
[DEBUG] [2020-10-29 08:05:14,493] [1863:140046620854080] - component_properties.py[line:118]: has_train_data: False, has_eval_data: False, has_normal_data: True
[DEBUG] [2020-10-29 08:05:14,493] [1863:140046620854080] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0003848075866699219s
[DEBUG] [2020-10-29 08:05:14,493] [1863:140046620854080] - model_base.py[line:210]: In extract_data, data input: {'args.data': <arch.api.impl.based_1x.table.DTable object at 0x7f5a0aee5ac8>}
[DEBUG] [2020-10-29 08:05:14,493] [1863:140046620854080] - model_base.py[line:87]: func: <bound method DataIO.fit of <federatedml.util.data_io.DataIO object at 0x7f5a0aee50f0>>
[INFO] [2020-10-29 08:05:14,493] [1863:140046620854080] - data_io.py[line:141]: start to read dense data and change data to instance
[DEBUG] [2020-10-29 08:05:14,494] [1863:140046620854080] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0004024505615234375s
[DEBUG] [2020-10-29 08:05:14,494] [1863:140046620854080] - data_io.py[line:95]: header is x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19
[DEBUG] [2020-10-29 08:05:14,494] [1863:140046620854080] - data_io.py[line:96]: sid_name is id
[DEBUG] [2020-10-29 08:05:14,526] [1863:140046620854080] - profile_util.py[line:34]: data_io.py:162 call mapValues, takes 0.03212904930114746s
[DEBUG] [2020-10-29 08:05:14,564] [1863:140046620854080] - profile_util.py[line:34]: data_io.py:244 call mapValues, takes 0.03691744804382324s
[DEBUG] [2020-10-29 08:05:14,564] [1863:140046620854080] - model_base.py[line:99]: saved_result is : [<arch.api.impl.based_1x.table.DTable object at 0x7f2586ec4ba8>], data_output: <arch.api.impl.based_1x.table.DTable object at 0x7f2586ec4ba8>
[DEBUG] [2020-10-29 08:05:14,594] [1863:140046620854080] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.02979254722595215s
[DEBUG] [2020-10-29 08:05:14,596] [1863:140046620854080] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008802413940429688s
[DEBUG] [2020-10-29 08:05:14,615] [1863:140046620854080] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.0006377696990966797s
[INFO] [2020-10-29 08:05:14,625] [1863:140046620854080] - pipelined_model.py[line:72]: Save dataio_0 dataio DataIOMeta buffer
[INFO] [2020-10-29 08:05:14,625] [1863:140046620854080] - pipelined_model.py[line:72]: Save dataio_0 dataio DataIOParam buffer
[INFO] [2020-10-29 08:05:14,630] [1863:140046620854080] - pipelined_model.py[line:77]: Save dataio_0 dataio successfully
[INFO] [2020-10-29 08:05:14,670] [1863:140046620854080] - task_executor.py[line:160]: task 202010290805128735466_dataio_0 host 10000 start time: 2020-10-29 08:05:14
[INFO] [2020-10-29 08:05:14,670] [1863:140046620854080] - task_executor.py[line:161]: task 202010290805128735466_dataio_0 host 10000 end time: 2020-10-29 08:05:14
[INFO] [2020-10-29 08:05:14,671] [1863:140046620854080] - task_executor.py[line:162]: task 202010290805128735466_dataio_0 host 10000 takes 0.523s
[INFO] [2020-10-29 08:05:14,671] [1863:140046620854080] - task_executor.py[line:164]: finish 202010290805128735466 dataio_0 202010290805128735466_dataio_0 host 10000 success task
