[INFO] [2020-10-29 08:04:50,130] [1428:140340862109504] - task_executor.py[line:121]: run 202010290804483462984 dataio_0 202010290804483462984_dataio_0 guest 9999 task
[INFO] [2020-10-29 08:04:50,130] [1428:140340862109504] - task_executor.py[line:122]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'job_parameters': {'work_mode': 0, 'processors_per_node': 1, 'align_task_input_data_partition': True, 'model_id': 'arbiter-10000#guest-9999#host-10000#model', 'model_version': '202010290804483462984'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'local': {'role': 'guest', 'party_id': 9999}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[INFO] [2020-10-29 08:04:50,131] [1428:140340862109504] - task_executor.py[line:123]: {'data': {'data': ['args.train_data']}}
[DEBUG] [2020-10-29 08:04:50,131] [1428:140340862109504] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0005719661712646484s
[INFO] [2020-10-29 08:04:50,132] [1428:140340862109504] - task_executor.py[line:202]: start save as task 202010290804483462984_dataio_0 input data table fate_flow_test_breast_hetero breast_hetero_guest
[DEBUG] [2020-10-29 08:04:50,132] [1428:140340862109504] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0005052089691162109s
[DEBUG] [2020-10-29 08:04:50,141] [1428:140340862109504] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.009009838104248047s
[INFO] [2020-10-29 08:04:50,145] [1428:140340862109504] - task_executor.py[line:218]: save as task 202010290804483462984_dataio_0 input data table to 202010290804483462984_dataio_0_guest_9999 breast_hetero_guest done
[DEBUG] [2020-10-29 08:04:50,272] [1428:140340862109504] - component_properties.py[line:67]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 9999}, 'job_parameters': {'work_mode': 0, 'processors_per_node': 1, 'align_task_input_data_partition': True, 'model_id': 'arbiter-10000#guest-9999#host-10000#model', 'model_version': '202010290804483462984'}, 'role': {'guest': [9999], 'host': [10000], 'arbiter': [10000]}, 'local': {'role': 'guest', 'party_id': 9999}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[DEBUG] [2020-10-29 08:04:50,272] [1428:140340862109504] - component_properties.py[line:74]: need_run: True, need_cv: False
[DEBUG] [2020-10-29 08:04:50,272] [1428:140340862109504] - component_properties.py[line:118]: has_train_data: False, has_eval_data: False, has_normal_data: True
[DEBUG] [2020-10-29 08:04:50,273] [1428:140340862109504] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.000782012939453125s
[DEBUG] [2020-10-29 08:04:50,274] [1428:140340862109504] - model_base.py[line:210]: In extract_data, data input: {'args.data': <arch.api.impl.based_1x.table.DTable object at 0x7f9e8d139b00>}
[DEBUG] [2020-10-29 08:04:50,274] [1428:140340862109504] - model_base.py[line:87]: func: <bound method DataIO.fit of <federatedml.util.data_io.DataIO object at 0x7f9e8d139160>>
[INFO] [2020-10-29 08:04:50,274] [1428:140340862109504] - data_io.py[line:141]: start to read dense data and change data to instance
[DEBUG] [2020-10-29 08:04:50,274] [1428:140340862109504] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0005545616149902344s
[DEBUG] [2020-10-29 08:04:50,275] [1428:140340862109504] - data_io.py[line:95]: header is y,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9
[DEBUG] [2020-10-29 08:04:50,275] [1428:140340862109504] - data_io.py[line:96]: sid_name is id
[DEBUG] [2020-10-29 08:04:50,307] [1428:140340862109504] - profile_util.py[line:34]: data_io.py:155 call mapValues, takes 0.031771183013916016s
[DEBUG] [2020-10-29 08:04:50,318] [1428:140340862109504] - profile_util.py[line:34]: data_io.py:158 call mapValues, takes 0.010182380676269531s
[DEBUG] [2020-10-29 08:04:50,354] [1428:140340862109504] - profile_util.py[line:34]: data_io.py:241 call join, takes 0.036338090896606445s
[DEBUG] [2020-10-29 08:04:50,355] [1428:140340862109504] - model_base.py[line:99]: saved_result is : [<arch.api.impl.based_1x.table.DTable object at 0x7f8a8b851b70>], data_output: <arch.api.impl.based_1x.table.DTable object at 0x7f8a8b851b70>
[DEBUG] [2020-10-29 08:04:50,387] [1428:140340862109504] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.031980276107788086s
[DEBUG] [2020-10-29 08:04:50,390] [1428:140340862109504] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0013394355773925781s
[DEBUG] [2020-10-29 08:04:50,421] [1428:140340862109504] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.0005195140838623047s
[INFO] [2020-10-29 08:04:50,432] [1428:140340862109504] - pipelined_model.py[line:72]: Save dataio_0 dataio DataIOMeta buffer
[INFO] [2020-10-29 08:04:50,433] [1428:140340862109504] - pipelined_model.py[line:72]: Save dataio_0 dataio DataIOParam buffer
[INFO] [2020-10-29 08:04:50,437] [1428:140340862109504] - pipelined_model.py[line:77]: Save dataio_0 dataio successfully
[INFO] [2020-10-29 08:04:50,460] [1428:140340862109504] - task_executor.py[line:160]: task 202010290804483462984_dataio_0 guest 9999 start time: 2020-10-29 08:04:49
[INFO] [2020-10-29 08:04:50,460] [1428:140340862109504] - task_executor.py[line:161]: task 202010290804483462984_dataio_0 guest 9999 end time: 2020-10-29 08:04:50
[INFO] [2020-10-29 08:04:50,460] [1428:140340862109504] - task_executor.py[line:162]: task 202010290804483462984_dataio_0 guest 9999 takes 0.522s
[INFO] [2020-10-29 08:04:50,460] [1428:140340862109504] - task_executor.py[line:164]: finish 202010290804483462984 dataio_0 202010290804483462984_dataio_0 guest 9999 success task
